# Generated by Django 3.0.7 on 2020-06-30 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default=79604821986, max_length=11),
            preserve_default=False,
        ),
    ]
